language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt
  - python setup.py install
  - pip install coveralls
script: CXX=clang++ nosetests --with-coverage --cover-package=raco --logging-level=DEBUG
after_success:
  - coveralls
